swagger: '2.0'
info:
  title: "Cloud Night - Serverless API in GCP"
  description: "Sample API on Cloud Endpoints with Google Cloud Serverless compute environments as backends (Cloud Functions, Cloud Run, Appengine Standard)"
  version: "1.0.0"
host: "esp-e3mqxk2nmq-uc.a.run.app"
schemes:
  - "https"
produces:
  - "application/json"
paths:
  "/functions":
    get:
      summary: "Greet a user"
      operationId: "hello-functions"
      x-google-backend:
        address: "https://us-central1-cloud-night-2019.cloudfunctions.net/cloud-night-function"
      parameters:
        - 
          in: query
          name: "name"
          type: string
          description: "The user name"
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  "/run":
    get:
      summary: "Greet a user"
      operationId: "hello-run"
      x-google-backend:
        address: "https://cloud-night-run-e3mqxk2nmq-uc.a.run.app/"
      parameters:
        - 
          in: query
          name: "name"
          type: string
          description: "The user name"
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  "/appengine":
    get:
      summary: "Greet a user"
      operationId: "hello-appengine"
      x-google-backend:
        address: "https://cloud-night-2019.appspot.com/"
        jwt_audience: 1091986106428-s22tc8u871u8jndsom6pq8br5s33tk1q.apps.googleusercontent.com
      parameters:
        - 
          in: query
          name: "name"
          type: string
          description: "The user name"
      responses:
        '200':
          description: A successful response
          schema:
            type: string
  "/lambda":
    get:
      summary: "Greet a user"
      operationId: "hello-lambda"
      x-google-backend:
        address: "https://qfbavncku8.execute-api.us-east-2.amazonaws.com/default/lambda-java"
      parameters:
        - 
          in: query
          name: "name"
          type: string
          description: "The user name"
      responses:
        '200':
          description: A successful response
          schema:
            type: string


            
            

